version: "3.9"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass my_password_redis
    environment:
      - name=value

  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - ./default.env
    depends_on:
      - redis
